variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN"    
  script:
    - docker build --pull -t matthewgall/dnsjson.com:latest .
    - docker push matthewgall/dnsjson.com:latest
