#!/bin/bash

if [ "$1" = "all" ]; then
  TARGETS=$(kubectx)
else
  TARGETS=$1
fi

echo "==================================================="
while IFS= read -r line
do
  echo "Deploying to ${line}"
  echo "==================================================="

  kubectx "$line" > /dev/null
  cat k8s.yml | envsubst | kubectl apply -n ${NAMESPACE} -f -

  echo ""
  echo "==================================================="
done <<< $TARGETS
